### ISSUE TITLE
I can't see the mesh in the video

### ISSUE THREAD

**Issue by Daixinxin-cc** [xiexh20/behave-dataset#1] opened 2022-05-08 08:48 UTC
Hi,

I have run your code, but the result in the video is like this, I can't see the mesh of kinect1 and kinect2. what's the problem?
![微信图片_20220508104755](https://user-images.githubusercontent.com/57379418/167288789-39471e97-34f0-48ab-8a33-f6b008002ee8.png)

**Comment by xiexh20** [comment] 2022-05-08 11:34
hi, which sequence did you use?  can you verify the SMPL registration is there inside the folder SEQ_NAME/frame_time/person/?

**Comment by Daixinxin-cc** [comment] 2022-05-09 14:43
> hi, which sequence did you use? can you verify the SMPL registration is there inside the folder SEQ_NAME/frame_time/person/?

I use Date01_Sub01_backpack_back, 
the content of person folder
![1652107254(1)](https://user-images.githubusercontent.com/57379418/167434645-cfbe9b70-0489-4eb2-bb8e-fdaf1ff2f79c.png)
the content of fit02 folder
![d5f17160d4c6d3b7a266410c39fc5a2](https://user-images.githubusercontent.com/57379418/167434811-cd02e554-7929-4dd8-a15b-f80c7280bbff.png)

I think the person_fit.ply is the SMPL registration???

**Comment by xiexh20** [comment] 2022-05-09 19:18
Hi, I checked this sequence, it does not have annotation for frame t0003.000. And the visualization code won't load this frame either as it is not there. Where did you get this frame?

**Comment by Daixinxin-cc** [comment] 2022-05-09 19:26
> Hi, I checked this sequence, it does not have annotation for frame t0003.000. And the visualization code won't load this frame either as it is not there. Where did you get this frame?
i can't see the mesh of each frame of each sequence, not one frame and one sequence
i download the behave data on your websit

**Comment by xiexh20** [comment] 2022-05-09 23:11
I am able to render the annotations for the sequences you mentioned. 
Did you follow my instructions exactly?
and what did you get after running this demo command? 
`python behave_demo.py -s BEHAVE_PATH/sequences/Date04_Sub05_boxlong -v YOUR_VISUALIZE_PATH -vc`

**Comment by Daixinxin-cc** [comment] 2022-05-10 06:33
> I am able to render the annotations for the sequences you mentioned. Did you follow my instructions exactly? and what did you get after running this demo command? `python behave_demo.py -s BEHAVE_PATH/sequences/Date04_Sub05_boxlong -v YOUR_VISUALIZE_PATH -vc`

like this
https://user-images.githubusercontent.com/57379418/167563126-f5f16a78-9aa4-4acb-91f9-ef58cdb4466b.mp4

**Comment by xiexh20** [comment] 2022-05-10 17:04
I am not able to reproduce your results.
Please provide **detailed instructions** to reproduce your issue. 
Or to further debug, you could check if the rendered image here https://github.com/xiexh20/behave-dataset/blob/main/behave_demo.py#L70 is fully white or not

**Comment by mnauf** [comment] 2022-05-16 10:26
I am having the same issue. @xiexh20 to reproduce this issue, please try this out on a new Linux machine. You might have a few required dependencies already installed on your existing machine.

P.S. @Daixinxin-cc were you able to solve it?

**Comment by mnauf** [comment] 2022-05-16 12:23
@bharat-b7 Will you also be able to look into this, please

**Comment by Daixinxin-cc** [comment] 2022-05-16 12:27
> I am not able to reproduce your results.
> Please provide **detailed instructions** to reproduce your issue.
> Or to further debug, you could check if the rendered image here https://github.com/xiexh20/behave-dataset/blob/main/behave_demo.py#L70 is fully white or not

No. so you solve this on a new linux machine?

**Comment by Daixinxin-cc** [comment] 2022-05-16 12:55
> I am having the same issue. @xiexh20 to reproduce this issue, please try this out on a new Linux machine. You might have a few required dependencies already installed on your existing machine.
> 
> P.S. @Daixinxin-cc were you able to solve it?

No. so you solve this on a new linux machine?

**Comment by mnauf** [comment] 2022-05-16 12:58
I dumped the result of line 70 using cv2.imwrite(). This is what it shows. This is an entire black image. @Daixinxin-cc Is this the same for you?
![lala](https://user-images.githubusercontent.com/41832069/168597604-0e4c935b-63d7-43d8-896b-32379d8c1fb6.jpg)

**Comment by xiexh20** [comment] 2022-05-16 19:36
@mnauf it is normal that the rendered image is fully black, because the rendered image is in the range of 0-1. it is converted to 0-255 before saving otherwise the image will be black. 
which OpenCV version are you using? if you are using a conda env, can you share your env configuration? (i.e. the output of `conda env export > environment.yml`)

**Comment by mnauf** [comment] 2022-05-17 07:32
cv2 version is 4.5.5.64. Sending yml file in a while

**Comment by mnauf** [comment] 2022-05-17 08:23
Please find the file here
https://drive.google.com/file/d/10WBotkDxLLzl30Ovtqs2V9G-Fkt53Dht/view?usp=sharing

**Comment by mnauf** [comment] 2022-05-17 08:24
Please find the file here
https://drive.google.com/file/d/10WBotkDxLLzl30Ovtqs2V9G-Fkt53Dht/view?usp=sharing

**Comment by mnauf** [comment] 2022-05-17 08:25
@xiexh20 
Please find the file here
https://drive.google.com/file/d/1uSEaj7BSCa1QjPklm-utbwglHDNDQCJT/view?usp=sharing

**Comment by xiexh20** [comment] 2022-05-17 15:30
Hi, it is due to a pytorch3d bug, see [issue](https://github.com/facebookresearch/pytorch3d/issues/1185).
The latest pytorch3d (0.6.2) has a bug for the PerspectiveCamera projection, I pushed a quick fix for this. But I suggest you use pytorch3d<=0.5 until this bug is fixed.

**Comment by mnauf** [comment] 2022-05-18 06:40
@xiexh20 Worked for me. [Here](https://drive.google.com/file/d/1YaNIxfHBxlOvFXh9cjdd38uFcE9EmhGY/view?usp=sharing) are the results. Thanks a ton! I think we can now mark the issue as resolved.

**Closed as completed** 2022-07-19 09:35 UTC

**Comment by supriya305** [comment] 2022-08-31 05:39
I am getting the same error as @Daixinxin-cc. I have pytorch3d version 0.3. I tried it for following sequences, Date01_Sub01_backpack_back, Date03_Sub03_stool_lift, Date03_Sub04_backpack_hand, Date03_Sub05_basketball etc. For all, I was not able to see the mesh  in both kinect1 and kincet2.
![image](https://user-images.githubusercontent.com/46373773/187600407-9282d710-3126-4a7c-a7b1-5429d464960f.png)

I am using conda env. This is my environment.yml file. 
https://drive.google.com/file/d/1dwj81iFLQdIVc2m77KVS3WV0N38M38Zh/view?usp=sharing
@xiexh20 Can you please look into this?
